--Creamos usuarios para poder hacer pruebas
CREATE USER ADM1 
IDENTIFIED BY adm1adm1
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP;

CREATE USER DIS1 
IDENTIFIED BY dis1dis1
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP;

CREATE USER jug1 
IDENTIFIED BY jug1jug1
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP;


--DROP de usuarios
DROP USER ADM1;
DROP USER DIS1;
DROP USER jug1;



--Creamos los ROLES
CREATE ROLE ADMINISTRADOR
NOT IDENTIFIED;

CREATE ROLE JUGADOR
NOT IDENTIFIED;

CREATE ROLE DISENIADOR
NOT IDENTIFIED;

-- DROP de ROLES
DROP ROLE ADMINISTRADOR;
DROP ROLE JUGADOR;
DROP ROLE DISENIADOR;

--Asignamos los privilegios a ROL ADMINISTRADOR
GRANT CREATE SESSION TO ADMINISTRADOR;
